# SPDX-FileCopyrightText: 2013 Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
#
# SPDX-License-Identifier: MIT

# This makefile is purposefully kept simple to support GNU and BSD make.

EXAMPLE_NAME = signal

SOURCES = $(EXAMPLE_NAME).c
OBJECTS = $(EXAMPLE_NAME).o
BINARY = $(EXAMPLE_NAME)
LIBS = -lurcu-signal

include ../Makefile.examples.template
